version: "3.9"
services:
  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "postgres1"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pyro127"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../sql_init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - common-network

networks:
  common-network:
    driver: bridge
    name: "common-network"
