version: "3.9"
services:
  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "postgres1"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pyro127"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../sql_init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
