# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, DatabaseClient):
        DatabaseClient.setObjectName("DatabaseClient")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(DatabaseClient)
        self.horizontalLayoutWidget_2.setMinimumWidth(1300)
        self.horizontalLayoutWidget_2.setMinimumHeight(900)
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayoutWidget_2.resize(1000, 800)
        self.mainLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.mainLayout.setContentsMargins(15, 15, 10, 5)
        self.mainLayout.setObjectName("mainLayout")
        self.commonLayout = QtWidgets.QVBoxLayout()
        self.commonLayout.setObjectName("commonLayout")
        self.filterLayout = QtWidgets.QHBoxLayout()
        self.filterLayout.setObjectName("filterLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label.setObjectName("label")
        self.filterLayout.addWidget(self.label)
        self.search_bar = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.search_bar.setObjectName("search_bar")
        self.search_bar.textChanged.connect(DatabaseClient.findSubstring)
        self.filterLayout.addWidget(self.search_bar)
        self.commonLayout.addLayout(self.filterLayout)
        self.commonLayout.addWidget(DatabaseClient.view)
        self.photoFilterButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.photoFilterButton.setObjectName("photoFilterButton")
        self.photoFilterButton.toggled.connect(DatabaseClient.radioButtonPhoto)
        self.button_group = QtWidgets.QButtonGroup(DatabaseClient)
        self.button_group.setObjectName("button_group")
        self.button_group.addButton(self.photoFilterButton)
        self.commonLayout.addWidget(self.photoFilterButton)
        self.photoFilterButton2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.photoFilterButton2.setObjectName("photoFilterButton2")
        self.photoFilterButton2.toggled.connect(DatabaseClient.radioButtonPhoto)
        self.photoFilterButton2.setChecked(True)
        self.button_group.addButton(self.photoFilterButton2)
        self.commonLayout.addWidget(self.photoFilterButton2)
        self.photoFilterButton3 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.photoFilterButton3.setObjectName("photoFilterButton3")
        self.photoFilterButton3.toggled.connect(DatabaseClient.radioButtonPhoto)
        self.button_group.addButton(self.photoFilterButton3)
        self.commonLayout.addWidget(self.photoFilterButton3)
        self.mainLayout.addLayout(self.commonLayout)
        self.buttonLayout = QtWidgets.QVBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.newButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.newButton.setObjectName("newButton")
        self.newButton.clicked.connect(DatabaseClient.newRecord)
        self.buttonLayout.addWidget(self.newButton)
        self.removeButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.removeButton.setObjectName("removeButton")
        self.removeButton.clicked.connect(DatabaseClient.view.removeOneRow)
        self.buttonLayout.addWidget(self.removeButton)
        self.editButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.editButton.setObjectName("editButton")
        self.editButton.clicked.connect(DatabaseClient.createSubwindow)
        self.buttonLayout.addWidget(self.editButton)
        self.mainLayout.addLayout(self.buttonLayout)
        self.retranslateUi(DatabaseClient)
        QtCore.QMetaObject.connectSlotsByName(DatabaseClient)

    def retranslateUi(self, DatabaseClient):
        _translate = QtCore.QCoreApplication.translate
        DatabaseClient.setWindowTitle(_translate("DatabaseClient", "DatabaseClient"))
        self.label.setText(_translate("DatabaseClient", "Search:"))
        self.photoFilterButton.setText(_translate("DatabaseClient", "Only with photo"))
        self.photoFilterButton2.setText(_translate("DatabaseClient", "All records"))
        self.photoFilterButton3.setText(_translate("DatabaseClient", "Without photo"))
        self.newButton.setText(_translate("DatabaseClient", "New record"))
        self.removeButton.setText(_translate("DatabaseClient", "Remove"))
        self.editButton.setText(_translate("DatabaseClient", "Edit"))
